<a href="https://colab.research.google.com/github/nfmanios-debug/Programacion_para_Ciencia_de_Datos-/blob/main/Taller06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Taller 06 - Filtrado de datos con *pandas***
---
<img src = "https://pandas.pydata.org/static/img/pandas.svg" alt = "pandas Logo" width = "70%">  </img>

En este taller revisaremos las opciones que nos ofrece **pandas** para filtrar
datos basándonos en una determinada condición.

In [58]:
# Vamos a seguir trabajando con el archivo de personas, así que en esta celda
# Importar Pandas y guarda en la variable df el archivo Excel
# ubicado en: https://github.com/luiscobo/poo/raw/refs/heads/main/Personas.xlsx
import pandas as pd
dfp = pd.read_excel("https://github.com/luiscobo/poo/raw/refs/heads/main/Personas.xlsx")
display(dfp)

,Cédula,Nombres,Edad,Genero,No de hijos,Nivel Educativo,Estrato Socio,Ingresos,Peso,Talla,Fuma,Usa Lentes,Tiene Casa,Tiene Automovil
0,1001023688,Caleb Figueroa,39,HOMBRE,1,SECUNDARIA,2,3182000,64,183,NO,NO,NO,NO
1,1011835272,Jonathan Perkins,46,HOMBRE,3,POSTGRADO,4,5607000,90,163,SI,SI,NO,NO
2,1012005757,John James,40,HOMBRE,0,SECUNDARIA,3,1633000,78,174,NO,NO,NO,SI
3,1012170500,James Fuentes,45,HOMBRE,3,PRIMARIA,3,2211000,81,162,NO,NO,NO,NO
4,1015693396,Adam Fischer,46,HOMBRE,3,PREGRADO,2,4149000,69,166,SI,NO,NO,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514,1988507026,Rebekah Page,36,MUJER,1,POSTGRADO,3,3886000,91,166,SI,SI,SI,NO
515,1992081101,Erika Love,29,MUJER,2,POSTGRADO,2,3424000,70,173,SI,SI,NO,NO
516,1993697068,Misty Barry,33,MUJER,1,SECUNDARIA,2,3079000,59,163,SI,SI,NO,SI
517,1994927121,Ruth Davis,28,MUJER,2,POSTGRADO,3,3380000,70,168,NO,NO,SI,NO
518,1999387013,Kimberly Ortega,49,MUJER,0,SECUNDARIA,2,5410000,69,168,SI,NO,SI,SI

In [59]:
# Muestre las primeras 10 personas del data frame de personas
dfp.Nombres.head(10)

0      Caleb Figueroa
1    Jonathan Perkins
2          John James
3       James Fuentes
4        Adam Fischer
5       Clayton Smith
6      Victor Holland
7      Richard Carter
8       Joshua Wright
9        Steven Mccoy
Name: Nombres, dtype: object

In [60]:
# Comencemos con algo fácil: presente todas columnas de de aquellas personas
# cuyo peso sea superior a 90 kilos.
dfw = dfp[dfp.Peso > 90]
display(dfw)

,Cédula,Nombres,Edad,Genero,No de hijos,Nivel Educativo,Estrato Socio,Ingresos,Peso,Talla,Fuma,Usa Lentes,Tiene Casa,Tiene Automovil
5,1016796462,Clayton Smith,52,HOMBRE,2,PREGRADO,2,3117000,98,177,SI,SI,SI,NO
16,1061139821,Jonathan Murray,41,HOMBRE,2,PREGRADO,4,5540000,96,179,SI,SI,SI,NO
20,1086351017,Joseph Brooks,48,HOMBRE,0,SECUNDARIA,2,1945000,93,167,NO,SI,SI,SI
22,1099918021,Jeffrey Neal,51,HOMBRE,2,PREGRADO,2,1612000,92,173,SI,SI,NO,NO
29,1126740132,Sean West,48,HOMBRE,1,POSTGRADO,2,4004000,96,174,SI,SI,NO,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502,1955490190,Laura Bailey,56,MUJER,0,PREGRADO,4,3542000,97,180,SI,SI,NO,SI
506,1969848135,Lynn Mckenzie,39,MUJER,0,PREGRADO,4,2680000,92,176,SI,SI,NO,SI
507,1972303058,Karen Mccoy,56,MUJER,2,POSTGRADO,4,2756000,96,162,SI,SI,SI,SI
512,1986546436,Kimberly Vargas,51,MUJER,3,PRIMARIA,2,4367000,94,180,SI,NO,NO,SI
514,1988507026,Rebekah Page,36,MUJER,1,POSTGRADO,3,3886000,91,166,SI,SI,SI,NO

In [61]:
# Ahora quiero ver la cantidad de personas del dataframe cuyo peso
# supere los 90 kilos

df90 = dfp[dfp.Peso > 90][['Peso']].count()
display(df90)

#

Peso    102
dtype: int64

In [62]:
# ¿Será posible ver solamente la edad de las personas cuyo peso no supere los 80 kilos?
df80 = dfp[dfp.Peso < 80].Edad
display(df80)

0      39
2      40
4      46
6      38
8      46
       ..
513    49
515    29
516    33
517    28
518    49
Name: Edad, Length: 275, dtype: int64

In [63]:
# Quiero ahora determinar la cantidad de personas cuya edad esté por encima de los 50 años
df50 = dfp[dfp.Edad > 50].Edad.count()
display(df50)

np.int64(98)

In [64]:
# ¿Cómo sería para obtener el promedio de la talla de las personas cuyos ingresos estén
# por encima del salario mínimo legal vigente?

smlv = 2000000
dfta = dfp[dfp.Ingresos > smlv ].Talla.mean()
display(dfta)

np.float64(171.65236051502146)

In [65]:
# Me encantaría ahora encontrar el promedio de edad de las personas que no tienen hijos
dfnh = dfp[dfp['No de hijos'] == 0]['Edad'].mean()
display(dfnh)

np.float64(38.697841726618705)

In [66]:
# Necesito saber el promedio de edad de las personas que fuman
dff = dfp[dfp['Fuma'] == 'NO']['Edad'].mean()
display(dff)

np.float64(38.97933884297521)

In [67]:
# Y veamos si son capaces de obtener la suma de los ingresos de las personas
# que tienen carro pero que están ubicadas entre las últimas 300 filas
dfc = dfp[dfp['Tiene Automovil'] == 'SI'][300:].Ingresos.sum()
display(dfc)

np.int64(0)

In [68]:
# ¿Y cuántas personas cuyo nombre inicia por "A" en mayúsculas hay en todo el dataframes?
dfa = dfp[dfp.Nombres.str.startswith('A')].Nombres.count()
display(dfa)

np.int64(43)

In [69]:
# Desearía saber el promedio del peso y la suma de la talla
# de las personas cuyo nivel educativo no es primaria
dfpa = dfp[dfp['Nivel Educativo'] != 'Primaria']
dfpaagg = dfpa.agg({
    'Peso': 'mean',
    'Talla': 'sum'
})
display(dfpaagg)

Peso        78.55106
Talla    89045.00000
dtype: float64

In [70]:
# ¿Eres capaz de encontrar la edad más pequeña entre todas las
# personas  que no usan lentes?

dfem = dfp[dfp['Usa Lentes'] == 'SI']['Edad'].min()

display(dfem)

21

In [71]:
# Y entre las últimas 100 personas, ¿Cuál es el Ingreso más alto de
# las personas que tienen 2 hijos o más?

dfia = dfp[dfp['No de hijos'] >=2 ].tail(100)['Ingresos'].max()

display(dfia)

5677000

In [72]:
# Ahora tengo el capricho de saber si hay forma de determina el promedio de la talla
# de todas las personas ubicadas entre las filas 100 y 200, pero que tengan
# una edad entre 30 y 40 años (puede usar el between)
dfia1 = dfp.iloc[100:200]
dfia2 = dfia1[dfp['Edad'].between(30, 40) ]['Talla'].mean()
display(dfia2)

/tmp/ipykernel_658/3764102150.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  dfia2 = dfia1[dfp['Edad'].between(30, 40) ]['Talla'].mean()

np.float64(171.20689655172413)

In [73]:
# ¿Será que puede determinarme ahora el promedio de ingresos de los hombres?
dfih = dfp[dfp['Genero'] == 'HOMBRE' ]['Ingresos'].mean()
display(dfih)

np.float64(3768316.7938931296)

In [74]:
# Y ahora quiero saber el promedio de los ingresos de las mujeres?
dfim = dfp[dfp['Genero'] == 'MUJER' ]['Ingresos'].mean()
display(dfim)

np.float64(3540369.6498054476)

### **Responda la siguiente pregunta:**

De acuerdo a los datos obtenidos anteriormente, ¿Cuál promedio es mayor? ¿El de los hombres o el de las mujeres?
Hombres

### **Reto final**

Están muy angustiados en la alcaldía porque parece que a mayor nivel educativo, hay más gordos. Presente la cantidad de gordos (personas que pesan más de 90 kilos) que hay en cada nivel
educativo y determine si es real o no la angustia del alcalde. Por cierto, peude usar la
operación `unique()` de una columna para saber los valores distintos de la columna del
nivel educativo.

In [75]:
dfgordos = dfp[dfp['Peso'] >=90 ].groupby('Nivel Educativo')['Peso'].count()
display(dfgordos)

Nivel Educativo
POSTGRADO     27
PREGRADO      27
PRIMARIA      26
SECUNDARIA    29
Name: Peso, dtype: int64

#### Segun el analisis de los datos no es cierto decir que a mayor grado academico hay mas poblacion con sobrepeso segun la muestra de datos