<a href="https://colab.research.google.com/github/nfmanios-debug/Programacion_para_Ciencia_de_Datos-/blob/main/Taller08_NM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Taller 08 - Agrupamiento *pandas***
---
<img src = "https://pandas.pydata.org/static/img/pandas.svg" alt = "pandas Logo" width = "70%">  </img>

En este taller revisaremos las opciones que nos ofrece **pandas** para crear
agrupación y funciones de agregación y resumen sobre dataframes.

In [41]:
# Vamos a seguir trabajando con el archivo de personas, así que en esta celda
# Importar Pandas y guarda en la variable df el archivo Excel
# ubicado en: https://github.com/luiscobo/poo/raw/refs/heads/main/Personas.xlsx
import pandas as pd
url = 'https://github.com/luiscobo/poo/raw/refs/heads/main/Personas.xlsx'
df = pd.read_excel(url)
df.head()

,Cédula,Nombres,Edad,Genero,No de hijos,Nivel Educativo,Estrato Socio,Ingresos,Peso,Talla,Fuma,Usa Lentes,Tiene Casa,Tiene Automovil
0,1001023688,Caleb Figueroa,39,HOMBRE,1,SECUNDARIA,2,3182000,64,183,NO,NO,NO,NO
1,1011835272,Jonathan Perkins,46,HOMBRE,3,POSTGRADO,4,5607000,90,163,SI,SI,NO,NO
2,1012005757,John James,40,HOMBRE,0,SECUNDARIA,3,1633000,78,174,NO,NO,NO,SI
3,1012170500,James Fuentes,45,HOMBRE,3,PRIMARIA,3,2211000,81,162,NO,NO,NO,NO
4,1015693396,Adam Fischer,46,HOMBRE,3,PREGRADO,2,4149000,69,166,SI,NO,NO,NO

In [42]:
# Para recordar un poquito
# Determinar el promedio del peso de las personas que no fuman y que tengan 2 o 3 hijos

df1 = df.loc[
    (df['Fuma'] == 'NO') &
    (df['No de hijos'].between(2, 3)),
    'Peso'].mean()
display(df1)

np.float64(78.78181818181818)

In [43]:
# Ejemplo 1: Agrupar por una columna
# Promedio de edad por cada estrato socioeconómico
df2 = df.groupby('Estrato Socio')['Edad'].mean()
display(df2)

Estrato Socio
2    39.017857
3    38.790055
4    38.741176
Name: Edad, dtype: float64

In [44]:
# Ejemplo 2: Agrupar por una columna
# Por cada nivel educativo, determinar cuál es el ingreso más alto

df3 = df.groupby('Nivel Educativo')['Ingresos'].max().sort_values()
display(df3)

Nivel Educativo
POSTGRADO     5655000
PREGRADO      5677000
PRIMARIA      5678000
SECUNDARIA    5687000
Name: Ingresos, dtype: int64

In [45]:
# Ejemplo 3: Agrupar por varias  columnas
# Calcular el promedio de edad por género y número de hijos
df4 = df.groupby(['Genero','No de hijos'])['Ingresos'].max().sort_values()
display(df4)

Genero  No de hijos
MUJER   0              5498000
        1              5595000
HOMBRE  3              5635000
        0              5655000
MUJER   2              5669000
        3              5677000
HOMBRE  2              5678000
        1              5687000
Name: Ingresos, dtype: int64

In [46]:
# Ejemplo 4: Agrupar por varias columnas
# Calcular la suma de ingresos por nivel educativo y estrato socioeconómico

df5 = df.groupby(['Nivel Educativo','Estrato Socio'])['Ingresos'].sum()
display(df5)

Nivel Educativo  Estrato Socio
POSTGRADO        2                177719000
                 3                137204000
                 4                192066000
PREGRADO         2                128770000
                 3                155953000
                 4                148956000
PRIMARIA         2                116038000
                 3                163710000
                 4                150354000
SECUNDARIA       2                183084000
                 3                201759000
                 4                141561000
Name: Ingresos, dtype: int64

In [47]:
# Ejemplo 5: Múltiples estadísticas
# Halle el promedio y la suma de edad agrupadas por la columna Fuma
df6 = df.groupby('Fuma').agg(
    Promedio_Edad=('Edad', 'mean'),
    Suma_Edad=('Edad', 'sum')
)
display(df6)

      Promedio_Edad  Suma_Edad
Fuma
NO        38.979339       9433
SI        38.732852      10729

In [49]:
# Ejemplo 6: Múltiples agregaciones
# Halle la suma, mayor y promedio de ingresos de las personas agrupadas género y si tiene casa
df6 = df.groupby('Fuma').agg(
    Promedio_Edad=('Edad', 'mean'),
    Suma_Edad=('Edad', 'sum')
)
display(df6)

      Promedio_Edad  Suma_Edad
Fuma
NO        38.979339       9433
SI        38.732852      10729

In [52]:
# Ejemplo 7: Múltiples agregaciones
# Halle la suma de los ingresos, el promedio del peso y el peso máximo de las personas agrupadas por nivel educativo

df7 = df.groupby('Nivel Educativo').agg(
    suma_ingresos=('Ingresos', 'sum'),
    Promedio_Peso=('Peso', 'mean'),
    Peso_Maximo=('Edad', 'max')
)
display(df7)

                 suma_ingresos  Promedio_Peso  Peso_Maximo
Nivel Educativo
POSTGRADO            506989000      77.868966           57
PREGRADO             433679000      79.200000           57
PRIMARIA             430102000      78.638655           57
SECUNDARIA           526404000      78.650000           57

In [56]:
# Ejemplo 8: Contar con groupby
# Cuántas personas hay en cada nivel educativo
df8 = df.groupby('Nivel Educativo').agg(
    total_personas=('Nivel Educativo', 'size')
)
display(df8)

                 total_personas
Nivel Educativo
POSTGRADO                   145
PREGRADO                    115
PRIMARIA                    119
SECUNDARIA                  140

In [58]:
# Ejemplo 9: Contar con groupby
# Si agrupamos por las columnas tiene casa y tiene automóvil, determinar cuántas personas hay

df9 = df.groupby(['Tiene Casa','Tiene Automovil']).size()
display(df9)

Tiene Casa  Tiene Automovil
NO          NO                 112
            SI                 120
SI          NO                 135
            SI                 152
dtype: int64

In [61]:
# Ejemplo 10: Groupby y filtros
# Ahora solo queremos trabajar con personas que tengan entre 30 y 40 años de edad,
# Y de ese grupo, determine cuántas personas hay en cada nivel educativo y
# cuál es el promedio de los ingresos de esas personas.

df10 = df.loc[df['Edad'].between(30, 40)].groupby('Nivel Educativo').agg(
    total_personas=('Nivel Educativo', 'size'),
    promedio_ingresos=('Ingresos', 'mean'))
display(df10)

                 total_personas  promedio_ingresos
Nivel Educativo
POSTGRADO                    43       3.464698e+06
PREGRADO                     30       3.895833e+06
PRIMARIA                     39       3.818077e+06
SECUNDARIA                   46       3.707109e+06