<a href="https://colab.research.google.com/github/nfmanios-debug/Programacion_para_Ciencia_de_Datos-/blob/main/Taller07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Taller 07 - Filtrado de datos con *pandas***
---
<img src = "https://pandas.pydata.org/static/img/pandas.svg" alt = "pandas Logo" width = "70%">  </img>

En este taller revisaremos las opciones que nos ofrece **pandas** para filtrar
datos basándonos en una determinada condición.

In [4]:
# Vamos a seguir trabajando con el archivo de personas, así que en esta celda
# importamos pandas y guardamos el archivo Excel en la variable df1:
# https://github.com/luiscobo/poo/raw/refs/heads/main/Personas.xlsx
import pandas as pd

df1 = pd.read_excel("https://github.com/luiscobo/poo/raw/refs/heads/main/Personas.xlsx")
display(df1)

,Cédula,Nombres,Edad,Genero,No de hijos,Nivel Educativo,Estrato Socio,Ingresos,Peso,Talla,Fuma,Usa Lentes,Tiene Casa,Tiene Automovil
0,1001023688,Caleb Figueroa,39,HOMBRE,1,SECUNDARIA,2,3182000,64,183,NO,NO,NO,NO
1,1011835272,Jonathan Perkins,46,HOMBRE,3,POSTGRADO,4,5607000,90,163,SI,SI,NO,NO
2,1012005757,John James,40,HOMBRE,0,SECUNDARIA,3,1633000,78,174,NO,NO,NO,SI
3,1012170500,James Fuentes,45,HOMBRE,3,PRIMARIA,3,2211000,81,162,NO,NO,NO,NO
4,1015693396,Adam Fischer,46,HOMBRE,3,PREGRADO,2,4149000,69,166,SI,NO,NO,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514,1988507026,Rebekah Page,36,MUJER,1,POSTGRADO,3,3886000,91,166,SI,SI,SI,NO
515,1992081101,Erika Love,29,MUJER,2,POSTGRADO,2,3424000,70,173,SI,SI,NO,NO
516,1993697068,Misty Barry,33,MUJER,1,SECUNDARIA,2,3079000,59,163,SI,SI,NO,SI
517,1994927121,Ruth Davis,28,MUJER,2,POSTGRADO,3,3380000,70,168,NO,NO,SI,NO
518,1999387013,Kimberly Ortega,49,MUJER,0,SECUNDARIA,2,5410000,69,168,SI,NO,SI,SI

In [25]:
# Determine cuántas mujeres mayores de 30 años no fuman
df2 = df1.loc[
    (df1['Genero'] == 'MUJER') &
    (df1['Edad'] > 30) &
    (df1['Fuma'] == 'NO'),
    'Genero'
].count()
display(df2)

np.int64(86)

In [26]:
# Muestre la cantidad de personas que viven en el estrato 2 o en el estrato 3
dfe2 = df1.loc[
    (df1['Estrato Socio'] == 2) |
    (df1['Estrato Socio'] == 3),
    'Estrato Socio'
].count()
display(dfe2)

np.int64(349)

In [18]:
# Muestre los nombres de los hombres con talla entre 167 y 173 cm
# y edad entre 50 y 57 años
dfe3 = df1.loc[
    (df1['Genero'] == 'HOMBRE') &
    (df1['Talla'].between(167, 173)) &
    (df1['Edad'].between(50, 57)),
    'Nombres'
]
display(dfe3)

11       Nicholas Green
22         Jeffrey Neal
32         Charles Wolf
36        Billy Calhoun
74       Connor Sweeney
81           Carl Craig
86           John Brown
100     Michael Sellers
105      Benjamin Avery
115        Brian Werner
160         Scott Cline
168      Zachary Rivera
176        Ryan Pearson
178       Herbert Avery
215    Donald Armstrong
225       Joseph Wilson
230         Eric Lowery
Name: Nombres, dtype: object

In [29]:
# Calcule el promedio del peso de las mujeres sin hijos, sin carro y sin casa
dfavg = df1.loc[
    (df1['Genero'] == 'MUJER') &
    (df1['No de hijos'] == 0) &
    (df1['Tiene Casa'] == 'NO') &
    (df1['Tiene Automovil'] == 'NO'),
    'Peso'
].mean()
display(dfavg)

np.float64(80.77777777777777)

In [27]:
# Calcule la suma de los ingresos de los hombres que tienen nivel educativo
# de primaria y que fuman
dfhep = df1.loc[
    (df1['Genero'] == 'HOMBRE') &
    (df1['Nivel Educativo'] == 'PRIMARIA') &
    (df1['Fuma'] == 'SI'),
    'Ingresos'
].sum()
display(dfhep)

np.int64(108735000)

In [30]:
# Cuente las personas que no tienen casa ni carro y cuyos ingresos
# son superiores a tres millones de pesos
dfnc3 = df1.loc[
    (df1['Tiene Casa'] == 'NO') &
    (df1['Tiene Automovil'] == 'NO') &
    (df1['Ingresos'] > 3000000),
    'Ingresos'
].count()
display(dfnc3)

np.int64(81)

In [32]:
# Imprima la edad más grande y luego los nombres de las personas que tienen esa edad
dfmax = df1['Edad'].max()
display(dfmax)

display(df1.loc[df1['Edad'] == dfmax, 'Nombres'])

57

11        Nicholas Green
32          Charles Wolf
109     William Santiago
129         Donald Hicks
141         William Tran
156        Brandon Green
160          Scott Cline
176         Ryan Pearson
188       Luke Rodriguez
189        Michael Davis
199    Maxwell Rodriguez
277       Tamara Patrick
338      Heather Nichols
345          Deborah Cox
357          Renee Crane
358          Mary Decker
395        Amy Rodriguez
409         Maria Valdez
421        Rachel Willis
427         Monica Young
Name: Nombres, dtype: object