<a href="https://colab.research.google.com/github/nfmanios-debug/Programacion_para_Ciencia_de_Datos-/blob/main/Taller04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Taller 04 - Introducción a *pandas***
---
<img src = "https://pandas.pydata.org/static/img/pandas.svg" alt = "pandas Logo" width = "70%">  </img>

En este material revisaremos las operaciones de lectura, selección e inspección de datos en **pandas**. Esta técnica es muy poderosa en la tarea de comprender los datos, conocer el contenido de los datasets y hacer análisis estadísticos de estos.

## **1. Importar *pandas***
---

En esta primera celda escriba el código en **Python** para importar **pandas**.

In [68]:
# Importar Pandas
import pandas as pd

## **2. Crear un dataframe**
---

Usando un diccionario de listas, construya un dataframe. Use al menos unas 4 columnas y 5 filas por columnas. Use sus propios datos.

In [69]:
# Crear el diccionario primero y luego el dataframe
import pandas as pd
from numpy import packbits

# Diccionario
dfcars = {
    "nombre": ["Corolla", "Mustang", "Civic"],
    "marca": ["Toyota", "Ford", "Honda"],
    "pais": ["Japon", "Estados Unidos", "Japón"],
    "transmision": ["Automática", "Manual", "Automática"]
}

# Dataframe
df1 = display(pd.DataFrame(dfcars))

    nombre   marca            pais transmision
0  Corolla  Toyota           Japon  Automática
1  Mustang    Ford  Estados Unidos      Manual
2    Civic   Honda           Japón  Automática

## **3.  Dataframe desde un archivo de datos**
---

Aquí vas a crear dataframes a partir de los archivos de datos en distintos formatos. Descargue el archivo, súbalos a Google Colab y lea los datos en un dataframe. Despliegue el contenido de las primeras 10 filas de cada dataframe.


> **IMPORTANTE:**

  1. Por favor descargue los archivos a continuación haciendo clic en el botón derecho y seleccionando la opción **Guardar enlace como..**:
     - Formato CSV: **[municipios.csv](https://github.com/luiscobo/poo/raw/refs/heads/main/municipios.csv)**
     - Formato Excel: **[Personas.xlsx](https://github.com/luiscobo/poo/raw/refs/heads/main/Personas.xlsx)**
     - Formato JSON: **[departamentos.json](https://github.com/luiscobo/poo/raw/refs/heads/main/departamentos.json)**
  
  2. Cargue este archivo en su sistema de archivos de **Google Colaboratory**. Para hacer esto:
     * Haga clic donde aparece el icono del directorio en la parte izquierda de la ventana en *Google Colaboratory*.
     * Después, haga clic en el icono **"Subir"**
     * Seleccione cada archivo que previamente descargó y haga clic en **"Aceptar"**.

In [70]:
# Leer cada archivo de datos descargado
import pandas as pd
# dataframes
df1 = display(pd.read_csv('/content/municipios.csv'))
df2 = display(pd.read_excel('/content/Personas.xlsx'))
df3 = display(pd.read_json('/content/departamentos.json'))

,código,nombre,poblaciónUrbana,poblaciónRural,departamento,esCapital
0,404,Abejorral,6724,12471,Antioquia,0
1,178,Ábrego,17287,21076,Norte de Santander,0
2,1090,Abriaquí,738,1337,Antioquia,0
3,89,Acacías,60918,11130,Meta,0
4,705,Acandí,5259,4246,Chocó,0
...,...,...,...,...,...,...
1117,145,Zarzal,32290,13391,Valle del Cauca,0
1118,971,Zetaquira,1057,3432,Boyacá,0
1119,895,Zipacón,2119,3512,Cundinamarca,0
1120,48,Zipaquirá,111025,15384,Cundinamarca,0
1121,103,Zona Bananera,5063,56309,Magdalena,0

,Cédula,Nombres,Edad,Genero,No de hijos,Nivel Educativo,Estrato Socio,Ingresos,Peso,Talla,Fuma,Usa Lentes,Tiene Casa,Tiene Automovil
0,1001023688,Caleb Figueroa,39,HOMBRE,1,SECUNDARIA,2,3182000,64,183,NO,NO,NO,NO
1,1011835272,Jonathan Perkins,46,HOMBRE,3,POSTGRADO,4,5607000,90,163,SI,SI,NO,NO
2,1012005757,John James,40,HOMBRE,0,SECUNDARIA,3,1633000,78,174,NO,NO,NO,SI
3,1012170500,James Fuentes,45,HOMBRE,3,PRIMARIA,3,2211000,81,162,NO,NO,NO,NO
4,1015693396,Adam Fischer,46,HOMBRE,3,PREGRADO,2,4149000,69,166,SI,NO,NO,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514,1988507026,Rebekah Page,36,MUJER,1,POSTGRADO,3,3886000,91,166,SI,SI,SI,NO
515,1992081101,Erika Love,29,MUJER,2,POSTGRADO,2,3424000,70,173,SI,SI,NO,NO
516,1993697068,Misty Barry,33,MUJER,1,SECUNDARIA,2,3079000,59,163,SI,SI,NO,SI
517,1994927121,Ruth Davis,28,MUJER,2,POSTGRADO,3,3380000,70,168,NO,NO,SI,NO
518,1999387013,Kimberly Ortega,49,MUJER,0,SECUNDARIA,2,5410000,69,168,SI,NO,SI,SI

,Departamento,Municipios,Capital,Superficie,Población,Densidad,IDH6,Fecha de creación
0,Amazonas,2,Leticia,109665,74541,0.70,0.768,1928
1,Antioquia,125,Medellín,63612,6299886,95.40,0.849,1856
2,Arauca,7,Arauca,23818,256527,10.40,0.804,1911
3,Atlántico,23,Barranquilla,3019,2403027,766.60,0.835,1905
4,Bogotá,0,Bogotá,1775,7878783,4146.00,0.904,1538
5,Bolívar,45,Cartagena de Indias,25978,2049083,76.20,0.823,1857
6,Boyacá,123,Tunja,23012,1272844,55.10,0.842,1857
7,Caldas,27,Manizales,7888,984128,124.00,0.828,1905
8,Caquetá,16,Florencia,88965,465477,5.00,0.752,1909
9,Casanare,19,Yopal,44490,344027,7.30,0.867,1973
10,Cauca,41,Popayán,29308,1354744,45.00,0.782,1857
11,Cesar,25,Valledupar,22905,1004064,42.20,0.810,1967
12,Chocó,31,Quibdó,46530,490327,10.20,0.731,1906
13,Córdoba,30,Montería,25020,1658090,63.30,0.798,1952
14,Cundinamarca,116,Bogotá,24210,2598245,102.30,0.837,1857
15,Guainía,1,Inírida,72238,40203,0.50,0.768,1963
16,Guaviare,4,San José del Guaviare,52957,107934,1.95,0.768,1977
17,Huila,37,Neiva,19890,1126314,54.50,0.807,1905
18,La Guajira,15,Riohacha,20848,902386,39.30,0.691,1898
19,Magdalena,30,Santa Marta,23188,1235425,52.00,0.785,1857
20,Meta,29,Villavicencio,85635,924843,10.20,0.822,1905
21,Nariño,64,Pasto,32820,1701840,50.00,0.773,1904
22,Norte de Santander,40,San José de Cúcuta,21648,1332335,61.00,0.799,1910
23,Putumayo,13,Mocoa,24885,337054,13.10,0.759,1905
24,Quindío,12,Armenia,1845,568473,308.10,0.832,1966
25,Risaralda,14,Pereira,4140,941283,223.50,0.839,1966
26,San Andrés y Providencia,2,San Andrés,52,75167,1410.00,0.834,1912
27,Santander,87,Bucaramanga,30537,2340988,65.80,0.879,1857
28,Sucre,26,Sincelejo,10670,834927,76.00,0.775,1966
29,Tolima,47,Ibagué,23562,1400203,58.90,0.804,1861
30,Valle del Cauca,42,Cali,22195,4520166,197.50,0.861,1910
31,Vaupés,3,Mitú,54135,42817,0.80,0.768,1910
32,Vichada,4,Puerto Carreño,100947,68575,0.60,0.768,1913

In [71]:
# Mostrar las primeras 10 filas de cada dataframe
import pandas as pd
#Municipios
df1 = display(pd.read_csv('/content/municipios.csv')['código'].nlargest(10))
#Personas
df2 = display(pd.read_excel('/content/Personas.xlsx')['Cédula'].nlargest(10))
#departamentos
df3 = display(pd.read_json('/content/departamentos.json')['Municipios'].nlargest(10))

474     1122
666     1121
987     1120
925     1119
455     1118
503     1117
130     1116
1107    1115
594     1114
691     1113
Name: código, dtype: int64

261    1999924535
518    1999387013
517    1994927121
516    1993697068
515    1992081101
514    1988507026
260    1987449033
513    1987223851
512    1986546436
259    1986294946
Name: Cédula, dtype: int64

1     125
6     123
14    116
27     87
21     64
29     47
5      45
30     42
10     41
22     40
Name: Municipios, dtype: int64

## **4. Inspección de datos**
---

In [72]:
# Crear un dataframe leyendo los datos del siguiente enlace
# (no tiene que descargar el archivo): https://github.com/luiscobo/poo/raw/refs/heads/main/municipios.csv

dfgit1 = display(pd.read_csv('https://github.com/luiscobo/poo/raw/refs/heads/main/municipios.csv'))

,código,nombre,poblaciónUrbana,poblaciónRural,departamento,esCapital
0,404,Abejorral,6724,12471,Antioquia,0
1,178,Ábrego,17287,21076,Norte de Santander,0
2,1090,Abriaquí,738,1337,Antioquia,0
3,89,Acacías,60918,11130,Meta,0
4,705,Acandí,5259,4246,Chocó,0
...,...,...,...,...,...,...
1117,145,Zarzal,32290,13391,Valle del Cauca,0
1118,971,Zetaquira,1057,3432,Boyacá,0
1119,895,Zipacón,2119,3512,Cundinamarca,0
1120,48,Zipaquirá,111025,15384,Cundinamarca,0
1121,103,Zona Bananera,5063,56309,Magdalena,0

In [73]:
# Obtener la información del dataframe
dfgit1info = pd.read_csv('https://github.com/luiscobo/poo/raw/refs/heads/main/municipios.csv').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1122 entries, 0 to 1121
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   código           1122 non-null   int64
 1   nombre           1122 non-null   object
 2   poblaciónUrbana  1122 non-null   int64
 3   poblaciónRural   1122 non-null   int64
 4   departamento     1122 non-null   object
 5   esCapital        1122 non-null   int64
dtypes: int64(4), object(2)
memory usage: 52.7+ KB

In [74]:
# Mostrar las primeras 10 filas del datafram
import pandas as pd
dfgit1 = display(pd.read_csv('https://github.com/luiscobo/poo/raw/refs/heads/main/municipios.csv').head(10))

,código,nombre,poblaciónUrbana,poblaciónRural,departamento,esCapital
0,404,Abejorral,6724,12471,Antioquia,0
1,178,Ábrego,17287,21076,Norte de Santander,0
2,1090,Abriaquí,738,1337,Antioquia,0
3,89,Acacías,60918,11130,Meta,0
4,705,Acandí,5259,4246,Chocó,0
5,215,Acevedo,6515,27098,Huila,0
6,323,Achí,4193,19258,Bolívar,0
7,727,Agrado,5366,3745,Huila,0
8,644,Agua de Dios,8405,2505,Cundinamarca,0
9,67,Aguachica,82976,11888,Cesar,0

In [75]:
# Mostrar las últimas 5 filas del dataframe
import pandas as pd
dfgit1 = display(pd.read_csv('https://github.com/luiscobo/poo/raw/refs/heads/main/municipios.csv').tail(10))

,código,nombre,poblaciónUrbana,poblaciónRural,departamento,esCapital
1112,53,Yumbo,107757,14961,Valle del Cauca,0
1113,616,Zambrano,10666,1022,Bolívar,0
1114,739,Zapatoca,5667,3224,Santander,0
1115,744,Zapayán,3649,5192,Magdalena,0
1116,240,Zaragoza,14137,16992,Antioquia,0
1117,145,Zarzal,32290,13391,Valle del Cauca,0
1118,971,Zetaquira,1057,3432,Boyacá,0
1119,895,Zipacón,2119,3512,Cundinamarca,0
1120,48,Zipaquirá,111025,15384,Cundinamarca,0
1121,103,Zona Bananera,5063,56309,Magdalena,0

In [76]:
# Mostrar las dimensiones del dataframe (filas y columnas)
import pandas as pd
dfgit1 = display(pd.read_csv('https://github.com/luiscobo/poo/raw/refs/heads/main/municipios.csv').shape)

(1122, 6)

In [77]:
# Determinar el nombre de las columnas solamente
import pandas as pd
dfgit1 = display(pd.read_csv('https://github.com/luiscobo/poo/raw/refs/heads/main/municipios.csv').columns)

Index(['código', 'nombre', 'poblaciónUrbana', 'poblaciónRural', 'departamento',
       'esCapital'],
      dtype='object')

In [78]:
# Determinar los tipos de las columnas
import pandas as pd
dfgit1 = display(pd.read_csv('https://github.com/luiscobo/poo/raw/refs/heads/main/municipios.csv').dtypes)

código              int64
nombre             object
poblaciónUrbana     int64
poblaciónRural      int64
departamento       object
esCapital           int64
dtype: object

In [79]:
# Presentar un resumen estadístico del dataframe
import pandas as pd
dfgit1 = display(pd.read_csv('https://github.com/luiscobo/poo/raw/refs/heads/main/municipios.csv').describe())

            código  poblaciónUrbana  poblaciónRural    esCapital
count  1122.000000     1.122000e+03     1122.000000  1122.000000
mean    561.500000     3.363703e+04    10198.901961     0.028520
std     324.037806     2.715733e+05    11719.567160     0.166529
min       1.000000     0.000000e+00      182.000000     0.000000
25%     281.250000     1.895500e+03     3697.250000     0.000000
50%     561.500000     4.995000e+03     6738.000000     0.000000
75%     841.750000     1.306500e+04    12722.000000     0.000000
max    1122.000000     8.063991e+06   173143.000000     1.000000